version: "3.9"

services:
   pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: team12
      restart: always